# OpenWeatherMap API configuration
api_key: ""  # Set via environment variable OPENWEATHERMAP_API_KEY

# Cities to monitor
cities:
  - Delhi
  - Mumbai
  - Chennai
  - Bangalore
  - Kolkata
  - Hyderabad

# Database configuration
database:
  type: "mongodb"
  host: "localhost"
  port: 27017
  name: "weather_monitoring"

# Alert thresholds
alert_thresholds:
  high_temperature: 35  # in Celsius
  low_temperature: 10   # in Celsius
  consecutive_updates: 2  # Number of consecutive updates to trigger an alert

# Data processing configuration
data_processing:
  update_interval: 300  # in seconds (5 minutes)

# Visualization configuration
visualization:
  update_interval: 3600  # in seconds (1 hour)